# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d5dd13ef15ce9f41491d0b2cd1bb15108db75e28e5542c796a8e6c6631ace2ba7b9451d3439c63c878ffc586997a3dbf9ddbb2bb8289c15e3d4086c389e2e5

test:
  secret_key_base: 7193759f07a60320d2d23e9c4a6873ff0ca6bba7e5487373c8b18865993edb2489a2acb9f1dce65f9d9af5509e81a8ffaece88333fb6d1fa5c90111556929cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
